engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- .bundle/
- bin/
- db/
- config/
- spec/
- "**/vendor/**/*"
