default: &default
  adapter: postgresql
  username: <%= ENV['DB_USERNAME'] %>
  pool:     <%= ENV['RAILS_MAX_THREADS'] %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DB_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST'] %>

production:
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
