# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89b0c3d2876f91155dfd35cb7a2e1de886c3b009a928d7fdfc78a2f3cd2108f8819fe2616790bba4e25e18edc4e0863b7b284a58972e53e4132a1730cea8bd18

test:
  secret_key_base: d5f13cafbd7cd96dd78c1eb5b808b7a0fcf173ff72290b1cf2a7cd154d6af12f8e971e3d2099fba2f2ff536b78f6fef1b06acf0a753b0d651455769f3bd8033a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
